### ISSUE TITLE
Panicked at "unable to create temporary texture"

### ISSUE THREAD

**Issue by tobii-dev** [unknowntrojan/egui-d3d9#11]
Hi, when I try to call 
```rust
egui_d3d9::app::EguiDx9::present(&mut self, dev: &IDirect3DDevice9)
```
I get this error: 
```
thread '<unnamed>' panicked at 'unable to create temporary texture: Error { code: HRESULT(0x8876086C), message: "" }'
```

<details><summary>Full stacktrace:</summary>
<p>

```
17:51:53 [ERROR] thread '<unnamed>' panicked at 'unable to create temporary texture: Error { code: HRESULT(0x8876086C), message: "" }': C:\Users\tobii\.cargo\git\checkouts\egui-d3d9-6163636d01cb9325\2fa7541\egui-d3d9\src\texman.rs:240
   0: backtrace::backtrace::trace<backtrace::capture::impl$1::create::closure_env$0>
             at C:\Users\tobii\.cargo\registry\src\index.crates.io-6f17d22bba15001f\backtrace-0.3.67\src\backtrace\mod.rs:53
   1: backtrace::capture::Backtrace::create
             at C:\Users\tobii\.cargo\registry\src\index.crates.io-6f17d22bba15001f\backtrace-0.3.67\src\capture.rs:176
   2: backtrace::capture::Backtrace::new
             at C:\Users\tobii\.cargo\registry\src\index.crates.io-6f17d22bba15001f\backtrace-0.3.67\src\capture.rs:140
   3: backtrace::capture::impl$8::default
             at C:\Users\tobii\.cargo\registry\src\index.crates.io-6f17d22bba15001f\backtrace-0.3.67\src\capture.rs:410
   4: alloc::vec::Vec::append_elements
             at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library\alloc\src\vec\mod.rs:1942
   5: alloc::vec::spec_extend::impl$4::spec_extend
             at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library\alloc\src\vec\spec_extend.rs:55
   6: alloc::vec::Vec::extend_from_slice
             at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library\alloc\src\vec\mod.rs:2386
   7: alloc::string::String::push_str
             at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library\alloc\src\string.rs:926
   8: alloc::string::impl$65::write_str
             at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library\alloc\src\string.rs:2861
   9: core::fmt::impl$0::write_str<alloc::string::String>
             at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library\core\src\fmt\mod.rs:199
  10: core::fmt::write
             at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library\core\src\fmt\mod.rs:1118
  11: core::fmt::Formatter::write_fmt
             at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library\core\src\fmt\mod.rs:1548
  12: windows::core::strings::hstring::impl$9::fmt
             at C:\Users\tobii\.cargo\registry\src\index.crates.io-6f17d22bba15001f\windows-0.48.0\src\core\strings\hstring.rs:149
  13: windows::core::strings::hstring::HSTRING::is_empty
             at C:\Users\tobii\.cargo\registry\src\index.crates.io-6f17d22bba15001f\windows-0.48.0\src\core\strings\hstring.rs:19
  14: core::fmt::builders::impl$3::finish::closure$0
             at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library\core\src\fmt\builders.rs:226
  15: core::result::Result::and_then
             at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library\core\src\result.rs:1319
  16: core::fmt::builders::DebugStruct::finish
             at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library\core\src\fmt\builders.rs:225
  17: core::ptr::drop_in_place<windows::core::strings::hstring::HSTRING>
             at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2\library\core\src\ptr\mod.rs:491
  18: core::fmt::impl$53::fmt<dyn$<core::fmt::Debug> >
             at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library\core\src\fmt\mod.rs:2258
  19: core::fmt::rt::Argument::fmt
             at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library\core\src\fmt\rt.rs:138
  20: core::fmt::write
             at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library\core\src\fmt\mod.rs:1094
  21: core::fmt::Write::write_fmt
             at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library\core\src\fmt\mod.rs:192
  22: std::panicking::begin_panic_handler::impl$0::fill::closure$0
             at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library\std\src\panicking.rs:544
  23: core::option::Option::get_or_insert_with
             at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library\core\src\option.rs:1651
  24: std::panicking::begin_panic_handler::PanicPayload::fill
             at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library\std\src\panicking.rs:542
  25: std::panicking::begin_panic_handler::impl$1::get
             at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library\std\src\panicking.rs:560
  26: <unknown>
  27: windows::core::error::GetErrorInfo
             at C:\Users\tobii\.cargo\registry\src\index.crates.io-6f17d22bba15001f\windows-0.48.0\src\core\error.rs:154
  28: std::panicking::begin_panic_handler::closure$0
             at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library\std\src\panicking.rs:582
  29: <unknown>
  30: enum2$<core::result::Result<tuple$<>,windows::core::error::Error> >::expect<tuple$<>,windows::core::error::Error>
             at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2\library\core\src\result.rs:1033
  31: egui_d3d9::texman::create_temporary_texture
             at C:\Users\tobii\.cargo\git\checkouts\egui-d3d9-6163636d01cb9325\2fa7541\egui-d3d9\src\texman.rs:240
  32: egui_d3d9::texman::new_texture_from_buffer
             at C:\Users\tobii\.cargo\git\checkouts\egui-d3d9-6163636d01cb9325\2fa7541\egui-d3d9\src\texman.rs:263
  33: egui_d3d9::texman::TextureManager::create_new_texture
             at C:\Users\tobii\.cargo\git\checkouts\egui-d3d9-6163636d01cb9325\2fa7541\egui-d3d9\src\texman.rs:88
  34: egui_d3d9::texman::impl$1::process_set_deltas::closure$0
             at C:\Users\tobii\.cargo\git\checkouts\egui-d3d9-6163636d01cb9325\2fa7541\egui-d3d9\src\texman.rs:58
  35: egui_d3d9::texman::TextureManager::process_set_deltas
             at C:\Users\tobii\.cargo\git\checkouts\egui-d3d9-6163636d01cb9325\2fa7541\egui-d3d9\src\texman.rs:41
  36: SE_GetProcAddressForCaller
  37: MsgWaitForMultipleObjectsEx
  38: NtUserSetWindowLong
  39: <unknown>

```

</p>
</details> 

The error seems to come from here: https://github.com/unknowntrojan/egui-d3d9/blob/b28a661163db170ebd996be59b9b87e267406e89/egui-d3d9/src/texman.rs#LL241C21-L241C21

But I have no idea why that would fail, or how to debug it.

According to the docs, at https://learn.microsoft.com/en-us/windows/win32/api/d3d9/nf-d3d9-idirect3ddevice9-createtexture

>In Windows Vista CreateTexture can create a texture from a system memory pointer allowing the application >more flexibility over the use, allocation and deletion of the system memory. For example, an application >could pass a GDI system memory bitmap pointer and get a Direct3D texture interface around it. Using a system >memory pointer with CreateTexture has the following restrictions:

>    - The pitch of the texture must be equal to the width multiplied by the number of bytes per pixel.
>    - Only textures with a single mipmap level are supported. The Levels argument must be 1.
>    - The Pool argument must be D3DPOOL_SYSTEMMEM.
>    - The pSharedHandle argument must be a valid pointer to a buffer that can hold the system memory point; >*pSharedHandle must be a valid pointer to system memory with a size in bytes of texture width * texture >height * bytes per pixel of the texture format.

But I think that is all correct in this case.

Here is the rest of the code:
```rust
use egui::Context;
use egui_d3d9::EguiDx9;
use std::sync::Once;
use windows::Win32::{
	Foundation::{HWND, LPARAM, LRESULT, WPARAM},
	Graphics::Direct3D9::IDirect3DDevice9,
	UI::WindowsAndMessaging::{CallWindowProcW, SetWindowLongPtrA, GWLP_WNDPROC, WNDPROC},
};

static mut APP: Option<EguiDx9<i32>> = None;

/// Original WNDPROC, so we can do CallWindowProcW(...) with it
static mut FN_ORG_WNDPROC: WNDPROC = None;

fn hello_ui(ctx: &Context, _frame: &mut i32) {
	log::trace!("I made it to hello_ui(..., _frame={_frame})"); // it reaches this line...
	egui::containers::Window::new("Main").show(ctx, |ui| {
		ctx.settings_ui(ui);
		ui.label("Hello world!");
		//ui.label(egui::RichText::new("Hello world").color(egui::Color32::WHITE));
	});
	log::trace!("I made past egui::containers::Window::new(...)!"); // and this one... But after that it crashes?
}

/// draw() gets called right before the original IDirect3DDevice9::Present() is called.
pub fn draw(dev: &IDirect3DDevice9, hwnd: HWND) {
	log::trace!("I made it to draw({hwnd:?})");
	static INIT: Once = Once::new();
	INIT.call_once(move || {
		unsafe {
			APP = Some(EguiDx9::init(dev, hwnd, hello_ui, 0, true));
			FN_ORG_WNDPROC = std::mem::transmute(SetWindowLongPtrA(
				hwnd,
				GWLP_WNDPROC,
				hk_wnd_proc as usize as _,
			));
		};
	});
	let app = unsafe { APP.as_mut().unwrap() };
	app.present(dev); //Crashes
	log::trace!("I made it past app.present(dev))"); // doesnt reach this line I think
}

unsafe extern "stdcall" fn hk_wnd_proc(
	hwnd: HWND,
	msg: u32,
	wparam: WPARAM,
	lparam: LPARAM,
) -> LRESULT {
	//This is okay because APP gets set before hooking this WNDPROC
	APP.as_mut().unwrap().wnd_proc(msg, wparam, lparam);
	CallWindowProcW(FN_ORG_WNDPROC, hwnd, msg, wparam, lparam)
}

```
\[EDIT\] Full code here: https://github.com/tobii-dev/blur-hooks-rs/blob/2f96fcb9d54a2dbfae2aca9258f4ccf5e62aefbb/src/gui/console.rs#L40

In the trace log file, I can see all the traces hit, except "I made it past app.present(dev))".
Any help testing or debugging this would be 💯

**Comment by lahed** [comment]
x2, same problem

**Comment by unknowntrojan** [comment]
I've had several people message me over this issue. I have no idea why this randomly breaks, my guess would be either color format or some kind of outdated DirectX module/api version. I have not had time to change the method by which we are updating textures from system memory. I think there was another way, but I forgot how it worked. I will take another look once I have time,

**Comment by amPerl** [comment]
I had this problem too, I'm still not sure what exactly was wrong with the texture data when passed in initially, but I noticed setting the `psharedhandle` to `null_mut` stopped it from crashing, which then led me to try doing it the `imgui-dx9-renderer` way as in https://github.com/Veykril/imgui-dx9-renderer/blob/master/src/lib.rs#L415-L429 and that seems to be working.

edit:
well, that was short lived. any update to textures still fails for probably the same reasons 🤷🏻 plus filling textures this way is slow as heck

**Comment by unknowntrojan** [comment]
> I had this problem too, I'm still not sure what exactly was wrong with the texture data when passed in initially, but I noticed setting the `psharedhandle` to `null_mut` stopped it from crashing, which then led me to try doing it the `imgui-dx9-renderer` way as in https://github.com/Veykril/imgui-dx9-renderer/blob/master/src/lib.rs#L415-L429 and that seems to be working.
> 
> edit: well, that was short lived. any update to textures still fails for probably the same reasons 🤷🏻 plus filling textures this way is slow as heck

It would help if someone had a system configuration or host program that causes this issue, so I can reproduce it. Otherwise, I'm completely in the dark.

**Comment by unknowntrojan** [comment]
@tobii-dev @lahed @amPerl Please follow up on this.

**Comment by tobii-dev** [comment]
I'm using the code I provided earlier to hook the d3d9 Device methods for rendering in an old win32 racing game called Blur, by building a proxy _d3d9.dll_.

In theory, the proxy method should work for any d3d9 app. If anyone has a good "example" app to test this on, I'll try that. In any case, I'm going to try to cook up a minimal example to see if this is an issue specific to Blur or with the library.

**Comment by tobii-dev** [comment]
> I had this problem too, I'm still not sure what exactly was wrong with the texture data when passed in initially, but I noticed setting the `psharedhandle` to `null_mut` stopped it from crashing, which then led me to try doing it the `imgui-dx9-renderer` way as in https://github.com/Veykril/imgui-dx9-renderer/blob/master/src/lib.rs#L415-L429 and that seems to be working.
> 
> edit:
> well, that was short lived. any update to textures still fails for probably the same reasons 🤷🏻 plus filling textures this way is slow as heck

FWIW I also tried imgui-d3d9-renderer, and although it doesn't crash, I couldn't get it to render over the game. I am however a 100% sure it's possible, because when I used the original C++ library, it rendered windows just fine.

**Comment by unknowntrojan** [comment]
I'm pretty sure it's an issue with some device state set by CreateDevice or something further down the setup. My most likely candidate is color format. Would still not make much sense as a bug though, so I'm not sure... I think I remember this issue appearing on WoW, so I'll be checking that out today. I'll let you know if I find anything. I'm not an expert on DX9, nor have I worked on it professionally, this project was a complete jump into cold water. So you all have the exact same chance of solving this as I do. Any further investigation is appreciated. I value this project as it's the only DX9 backend for egui right now, and I would like for most people to be able to use it. Once I solve this, I'm probably going to recode https://github.com/jac3km4/egui-d3d11 as I feel that one needs a fresh start. Trying to keep the ecosystem healthy, so to speak :)

**Comment by unknowntrojan** [comment]
Easier to fix than I had anticipated. Maybe I should have done this earlier. Fixed by 65209ea .

For those interested: I literally now just lock the texture into memory and copy bytes to it, instead of having the texture load stuff from memory in the first place. It's an extra copy, and a useless copy at that, but I've given up on Microsoft making sense.

**Comment by tobii-dev** [comment]
> Easier to fix than I had anticipated. Maybe I should have done this earlier. Fixed by [65209ea](https://github.com/unknowntrojan/egui-d3d9/commit/65209ea535c119cb7b1c070b7da02a877faff01d) .
> 
> For those interested: I literally now just lock the texture into memory and copy bytes to it, instead of having the texture load stuff from memory in the first place. It's an extra copy, and a useless copy at that, but I've given up on Microsoft making sense.

This solved my crashes, I can now get the window working! Thank you so much! I don't fully understand why the fix works (those ptrs looked wonky), but I finally got the window to draw. When I switch between Fullscreen <-> Windowed it still crashed, I had similar issues with imgui-d3d9.

![image](https://github.com/unknowntrojan/egui-d3d9/assets/77458451/982e6584-62c2-46cb-b215-446583ffe21b)


Other than this, egui has updated from  0.21 to 0.22, maybe it's worth it this crate to update as well.
In any case, a huge thank you from the Blur community <3

**Comment by unknowntrojan** [comment]
> This solved my crashes, I can now get the window working! Thank you so much! I don't fully understand why the fix works (those ptrs looked wonky), but I finally got the window to draw.

It's most likely the DirectX code checking compatibility or something. My guess is either the game used some kind of compatibility mode, old DirectX version, or something else. Whatever it was, it's the code rejecting the post-Vista version of initializing textures.

> When I switch between Fullscreen <-> Windowed it still crashed, I had similar issues with imgui-d3d9.

Feel free to open a new issue for the crash from switching from fullscreen to windowed.

> Other than this, egui has updated from 0.21 to 0.22, maybe it's worth it this crate to update as well.

I'll update egui in a sec. Thanks for letting me know.

> In any case, a huge thank you from the Blur community <3

No problem :) Have fun!
